name: Documentation
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v4
      name: Check out repository
    - name: Install Elm compiler
      run: |
        cd $GITHUB_WORKSPACE 
        ls
    - name: Run elm
      run: elm --help
